name       : rednotebook
version    : '2.24'
release    : 21
source     :
    - https://github.com/jendrikseipp/rednotebook/archive/v2.24.tar.gz : 575c05f61fab2add5258a3f8a22a35c6d25cee7f44412ae2ed5dcd0059453a91
homepage   : https://rednotebook.app
license    : GPL-2.0-or-later
component  : office.notes
summary    : A cross-platform journal
description: |
    RedNotebook is a modern desktop journal. It lets you format, tag and search your entries. You can also add pictures, links and customizable templates, spell check your notes, and export to plain text, HTML, Latex or PDF.
rundeps    :
    - libgtksourceview3
    - libwebkit-gtk
    - pyenchant
    - pyyaml
build      : |
    sed -i "s|2021|2022|g" rednotebook/info.py
    %python3_setup
install    : |
    %python3_install
