name       : rednotebook
version    : 2.0
release    : 1
source     :
    - https://github.com/jendrikseipp/rednotebook/archive/v2.0.tar.gz : 57c1a90550ecdf62c852d2533afa2c29fb99e8802a9b38d1c88241dbaad39612
license    : GPL-2.0
component  : office.notes
summary    : A cross-platform journal
description: |
    RedNotebook is a modern desktop journal. It lets you format, tag and search your entries. You
    can also add pictures, links and customizable templates, spell check your notes, and export to
    plain text, HTML, Latex or PDF.
rundeps    :
    - libwebkit-gtk
    - pyenchant
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
