name       : rednotebook
version    : '2.3'
release    : 4
source     :
    - https://github.com/jendrikseipp/rednotebook/archive/v2.3.tar.gz : 9db863fc27ef17f8e4d3ce3cd96af1e62d33aa7bf1eb229f708f1fd5ccc2eb22
license    : GPL-2.0
component  : office.notes
summary    : A cross-platform journal
description: |
    RedNotebook is a modern desktop journal. It lets you format, tag and search your entries. You
    can also add pictures, links and customizable templates, spell check your notes, and export to
    plain text, HTML, Latex or PDF.
rundeps    :
    - libwebkit-gtk
    - pyenchant
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
