name       : rednotebook
version    : 2.29.3
release    : 28
source     :
    - https://github.com/jendrikseipp/rednotebook/archive/refs/tags/v2.29.3.tar.gz : 9f98217cab22641bb2c5f8245a76a7a423757786705ec0b10a1e38eb1232339a
homepage   : https://rednotebook.app
license    : GPL-2.0-or-later
component  : office.notes
summary    : A cross-platform journal
description: |
    RedNotebook is a modern desktop journal. It lets you format, tag and search your entries. You can also add pictures, links and customizable templates, spell check your notes, and export to plain text, HTML, Latex or PDF.
rundeps    :
    - libgtksourceview4
    - libwebkit-gtk
    - pyenchant
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
